name: Print Name Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Your Name"
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
      - feature

jobs:
  print_name:
    runs-on: ubuntu-latest

    steps:
      - name: Print the name input
        run: echo "Hello, ${{ github.event.inputs.name }}!"
